### ISSUE TITLE
Persistance

### ISSUE THREAD

**Issue by johnvick** [anujdatar/cups-docker#2]
Thanks for this useful software, I run it in a Proxmox Ubuntu VM in a Docker container. It does what Google Cloud print used to do for me. Any word on adding persistence?

**Comment by anujdatar** [comment]
Hi John,

That's actually been on my todo list for a long time. Kinda slipped through the cracks. Thanks for reminding me. I just pushed an update that allows you to add a persistent volume. I have updated the docs as well. Docker hub should have the updated images now as well. Hope this helps.

Regards,
Anuj
