### ISSUE TITLE
Adding --no-install-recommends effectively removed all extra drivers

### ISSUE THREAD

**Issue by Korri** [anujdatar/cups-docker#5]
The package `printer-driver-all` [is a meta package, that _only_ recommends other packages](https://packages.ubuntu.com/focal/printer-driver-all).

After the update any instance depending on one of those packages is not non functional (my brother printer stopped working for example).

**Comment by anujdatar** [comment]
You are absolutely right. I missed that. I only have an HP printer, so I just need the `foo2zjs` package. It's done, I removed the `--no-install-recommends` flag, new build should be up in a few minutes once the github action completes.

Thanks,
Anuj
